"""Preregistered E5 episode-level conformal experiment.

This module keeps the E5 orchestration separate from the neural experiments.
It fits the frozen nonlinear least-squares estimator once, then treats each
eight-hour load episode as one independent scalar observation.  Test truth is
only generated by :func:`run_e5_primary`, after the write-once run sentinel has
been claimed.

Absolute temperatures are in degrees Celsius, conformity scores and interval
widths are in kelvin, time is in seconds, and load is per unit.  Expected
unbounded limits are represented by ``None`` plus an explicit status in JSON;
no JSON artifact contains IEEE NaN or infinity values.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
import math
from pathlib import Path
from typing import Callable, Mapping, Sequence

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .classical import NLSModel, NLSRefusal, fit_nls, predict_nls
from .diagnostics import (
    CoverageMetrics,
    beta_5_2_mapped_density_ratio,
    coverage_metrics,
    effective_sample_size,
    gaussian_kde_scott_density_ratio,
    one_sided_higher_quantile,
    split_conformal_upper_limits,
    weighted_conformal_upper_limits,
)
from .evidence import require_completed_primary, require_e1_passed
from .runstore import begin_primary_run, finish_primary_run, record_primary_failures
from .runtime import enforce_cpu_only_environment
from .synthetic_lab import (
    Schedule,
    make_e3_schedule,
    make_train_schedule,
    observe_hotspot_references,
    observe_record,
    simulate_truth,
)


FloatArray = NDArray[np.float64]

E5_SEED = 61_000
E5_ALPHA = 0.05
E5_CONFIDENCE = 0.95
E5_REFERENCE_BUDGET = 20
E5_CALIBRATION_EPISODES = 200
E5_TEST_EPISODES = 1_000
E5_UNLABELED_TARGET_EPISODES = 2_000
E5_IN_RANGE_SUPPORT_PU: tuple[float, float] = (0.60, 0.90)
E5_STRICT_CENTRES_PU: tuple[float, ...] = (1.00, 1.15, 1.30, 1.60)
E5_STRICT_BAND_WIDTH_PU = 0.05

# Separate NumPy SeedSequence streams prevent accidental reuse between the NLS
# observation streams in synthetic_lab and the episode-load distributions.
_STREAM_CALIBRATION = 100
_STREAM_EXCHANGEABLE_TEST = 101
_STREAM_STRICT_BASE = 110
_STREAM_UNLABELED_TARGET = 120
_STREAM_WEIGHTED_TEST = 121


@dataclass(frozen=True, slots=True)
class E5EpisodeDraws:
    """Frozen independent target-load draws for all preregistered E5 cases."""

    calibration_loads_pu: FloatArray
    exchangeable_test_loads_pu: FloatArray
    strict_test_loads_by_centre: tuple[tuple[float, FloatArray], ...]
    unlabeled_target_loads_pu: FloatArray
    weighted_test_loads_pu: FloatArray


@dataclass(frozen=True, slots=True)
class EpisodeBatch:
    """Scalar truth/prediction outcomes for independent eight-hour episodes."""

    target_loads_pu: FloatArray
    true_peaks_C: FloatArray
    predicted_peaks_C: FloatArray

    def __post_init__(self) -> None:
        arrays = (
            np.asarray(self.target_loads_pu, dtype=np.float64),
            np.asarray(self.true_peaks_C, dtype=np.float64),
            np.asarray(self.predicted_peaks_C, dtype=np.float64),
        )
        if any(array.ndim != 1 or array.size == 0 for array in arrays):
            raise ValueError("episode arrays must be non-empty and one-dimensional")
        if not (arrays[0].shape == arrays[1].shape == arrays[2].shape):
            raise ValueError("episode loads, truths, and predictions must align")
        if any(not np.all(np.isfinite(array)) for array in arrays):
            raise ValueError("episode arrays must contain only finite values")
        if np.any(arrays[0] <= 0.0):
            raise ValueError("episode target loads must be positive")

    @property
    def conformity_scores_K(self) -> FloatArray:
        """Return one true-minus-predicted peak score per episode [K]."""

        return np.asarray(self.true_peaks_C - self.predicted_peaks_C, dtype=np.float64)


def _readonly(values: ArrayLike) -> FloatArray:
    array = np.asarray(values, dtype=np.float64).copy()
    array.setflags(write=False)
    return array


def _validated_seed(seed: int) -> int:
    if isinstance(seed, bool) or not isinstance(seed, (int, np.integer)):
        raise TypeError("seed must be an integer")
    value = int(seed)
    if value < 0:
        raise ValueError("seed must be non-negative")
    return value


def _rng(seed: int, stream: int) -> np.random.Generator:
    return np.random.default_rng(
        np.random.SeedSequence([_validated_seed(seed), int(stream)])
    )


def e5_configuration() -> dict[str, object]:
    """Return the complete E5 protocol hashed into the primary access claim."""

    half_width = E5_STRICT_BAND_WIDTH_PU / 2.0
    strict_bands = [
        {
            "centre_pu": centre,
            "lower_pu": centre - half_width,
            "upper_pu": centre + half_width,
            "episodes": E5_TEST_EPISODES,
            "rng_stream": _STREAM_STRICT_BASE + index,
        }
        for index, centre in enumerate(E5_STRICT_CENTRES_PU)
    ]
    return {
        "alpha": E5_ALPHA,
        "confidence_level": E5_CONFIDENCE,
        "episode": {
            "duration_h": 8.0,
            "initial_load_pu": 0.75,
            "step_time_h": 4.0,
            "outcome": "maximum noise-free hot-spot temperature over full episode [degC]",
            "prediction": "maximum fixed-NLS hot-spot temperature over full episode [degC]",
        },
        "fit": {
            "fit_count": 1,
            "physics_mode": "structural_mismatch",
            "record": "E3 train record (48 h)",
            "reference_budget": E5_REFERENCE_BUDGET,
            "seed": E5_SEED,
        },
        "ordinary": {
            "calibration": {
                "distribution": "Uniform(0.60, 0.90 pu)",
                "episodes": E5_CALIBRATION_EPISODES,
                "rng_stream": _STREAM_CALIBRATION,
            },
            "exchangeable_test": {
                "distribution": "Uniform(0.60, 0.90 pu)",
                "episodes": E5_TEST_EPISODES,
                "rng_stream": _STREAM_EXCHANGEABLE_TEST,
            },
            "strict_shift_bands": strict_bands,
        },
        "quantile": "ceil((n_calibration + 1) * (1 - alpha)) higher rank",
        "seed": E5_SEED,
        "weighted": {
            "density_ratio": "Gaussian KDE q(x)/p(x), scipy Scott bandwidth",
            "interval_weights": "estimated density ratio only; no clipping/flooring",
            "known_ratio": "Beta(5,2) density divided by Uniform density on common mapped support",
            "strict_support_policy": "outside observed calibration hull => target mass 1 at +infinity",
            "target_distribution": "Beta(5,2) mapped to 0.60--0.90 pu",
            "test_episodes": E5_TEST_EPISODES,
            "test_rng_stream": _STREAM_WEIGHTED_TEST,
            "unlabeled_target_episodes": E5_UNLABELED_TARGET_EPISODES,
            "unlabeled_target_rng_stream": _STREAM_UNLABELED_TARGET,
        },
    }


def draw_e5_episode_loads(
    *,
    seed: int = E5_SEED,
    calibration_episodes: int = E5_CALIBRATION_EPISODES,
    test_episodes: int = E5_TEST_EPISODES,
    unlabeled_target_episodes: int = E5_UNLABELED_TARGET_EPISODES,
) -> E5EpisodeDraws:
    """Draw independent target loads using fixed, named RNG streams.

    The optional sizes support small unit fixtures.  The primary runner uses
    only the preregistered defaults embedded in :func:`e5_configuration`.
    """

    counts = {
        "calibration_episodes": calibration_episodes,
        "test_episodes": test_episodes,
        "unlabeled_target_episodes": unlabeled_target_episodes,
    }
    for name, value in counts.items():
        if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
            raise ValueError(f"{name} must be a positive integer")
    lower, upper = E5_IN_RANGE_SUPPORT_PU
    calibration = _rng(seed, _STREAM_CALIBRATION).uniform(
        lower, upper, size=calibration_episodes
    )
    exchangeable = _rng(seed, _STREAM_EXCHANGEABLE_TEST).uniform(
        lower, upper, size=test_episodes
    )
    half_width = E5_STRICT_BAND_WIDTH_PU / 2.0
    strict = tuple(
        (
            centre,
            _readonly(
                _rng(seed, _STREAM_STRICT_BASE + index).uniform(
                    centre - half_width,
                    centre + half_width,
                    size=test_episodes,
                )
            ),
        )
        for index, centre in enumerate(E5_STRICT_CENTRES_PU)
    )
    unlabeled = lower + (upper - lower) * _rng(
        seed, _STREAM_UNLABELED_TARGET
    ).beta(5.0, 2.0, size=unlabeled_target_episodes)
    weighted = lower + (upper - lower) * _rng(
        seed, _STREAM_WEIGHTED_TEST
    ).beta(5.0, 2.0, size=test_episodes)
    return E5EpisodeDraws(
        calibration_loads_pu=_readonly(calibration),
        exchangeable_test_loads_pu=_readonly(exchangeable),
        strict_test_loads_by_centre=strict,
        unlabeled_target_loads_pu=_readonly(unlabeled),
        weighted_test_loads_pu=_readonly(weighted),
    )


def validate_primary_episode_draws(draws: E5EpisodeDraws) -> None:
    """Fail closed unless every primary draw matches its frozen distribution support."""

    def require_vector_in_support(
        values: ArrayLike,
        *,
        label: str,
        expected_size: int,
        lower_pu: float,
        upper_pu: float,
    ) -> FloatArray:
        array = np.asarray(values, dtype=np.float64)
        if array.ndim != 1 or array.size != expected_size:
            raise RuntimeError(
                f"E5 {label} shape/count differs from preregistration"
            )
        if not np.all(np.isfinite(array)):
            raise RuntimeError(f"E5 {label} contains a non-finite load")
        if np.any(array < lower_pu) or np.any(array > upper_pu):
            raise RuntimeError(
                f"E5 {label} lies outside frozen support "
                f"[{lower_pu:.3f}, {upper_pu:.3f}] pu"
            )
        return array

    lower, upper = E5_IN_RANGE_SUPPORT_PU
    require_vector_in_support(
        draws.calibration_loads_pu,
        label="Uniform calibration loads",
        expected_size=E5_CALIBRATION_EPISODES,
        lower_pu=lower,
        upper_pu=upper,
    )
    require_vector_in_support(
        draws.exchangeable_test_loads_pu,
        label="Uniform exchangeable-test loads",
        expected_size=E5_TEST_EPISODES,
        lower_pu=lower,
        upper_pu=upper,
    )
    require_vector_in_support(
        draws.unlabeled_target_loads_pu,
        label="Beta-mapped unlabeled-target loads",
        expected_size=E5_UNLABELED_TARGET_EPISODES,
        lower_pu=lower,
        upper_pu=upper,
    )
    require_vector_in_support(
        draws.weighted_test_loads_pu,
        label="Beta-mapped weighted-test loads",
        expected_size=E5_TEST_EPISODES,
        lower_pu=lower,
        upper_pu=upper,
    )
    if tuple(centre for centre, _ in draws.strict_test_loads_by_centre) != (
        E5_STRICT_CENTRES_PU
    ):
        raise RuntimeError("E5 strict-shift band centres differ from preregistration")
    half_width = E5_STRICT_BAND_WIDTH_PU / 2.0
    for centre, loads in draws.strict_test_loads_by_centre:
        require_vector_in_support(
            loads,
            label=f"strict-shift {centre:.2f} pu-band loads",
            expected_size=E5_TEST_EPISODES,
            lower_pu=centre - half_width,
            upper_pu=centre + half_width,
        )


def make_e5_episode_schedule(target_load_pu: float) -> Schedule:
    """Generalise the frozen E3 step schedule to an arbitrary E5 target load."""

    target = float(target_load_pu)
    if not np.isfinite(target) or target <= 0.0:
        raise ValueError("target_load_pu must be finite and positive")
    template = make_e3_schedule(1.00)
    load = np.where(template.time_s < 4.0 * 3600.0, 0.75, target)
    load_half = np.where(template.time_s + 15.0 < 4.0 * 3600.0, 0.75, target)
    return replace(
        template,
        name=f"e5_episode_{target:.12g}pu",
        load_pu=_readonly(load),
        load_pu_half=_readonly(load_half),
        target_load_pu=target,
    )


def fit_e5_nls_once(
    *,
    seed: int = E5_SEED,
    truth_simulator: Callable[..., object] = simulate_truth,
    record_observer: Callable[..., object] = observe_record,
    reference_observer: Callable[..., object] = observe_hotspot_references,
    fitter: Callable[..., object] = fit_nls,
) -> NLSModel:
    """Fit the frozen NLS once on the structural-mismatch E3 train record."""

    train_truth = truth_simulator(
        make_train_schedule(), physics_mode="structural_mismatch"
    )
    observed = record_observer(train_truth, seed=seed)
    references = reference_observer(
        train_truth, budget=E5_REFERENCE_BUDGET, seed=seed
    )
    outcome = fitter(observed, references)
    if isinstance(outcome, NLSRefusal):
        raise RuntimeError(
            "E5 requires one available NLS fit; frozen estimator refused: "
            f"{outcome.reason_type}: {outcome.message}"
        )
    if not isinstance(outcome, NLSModel):
        raise TypeError("E5 NLS fitter returned an unsupported outcome")
    return outcome


def evaluate_episode_loads(
    target_loads_pu: ArrayLike,
    model: NLSModel,
    *,
    schedule_factory: Callable[[float], Schedule] = make_e5_episode_schedule,
    truth_simulator: Callable[..., object] = simulate_truth,
    model_predictor: Callable[[NLSModel, Schedule], object] = predict_nls,
) -> EpisodeBatch:
    """Evaluate noise-free truth and the fixed NLS peak for target loads."""

    loads = np.asarray(target_loads_pu, dtype=np.float64)
    if loads.ndim != 1 or loads.size == 0 or not np.all(np.isfinite(loads)):
        raise ValueError("target_loads_pu must be a non-empty finite 1-D array")
    true_peaks = np.empty(loads.size, dtype=np.float64)
    predicted_peaks = np.empty(loads.size, dtype=np.float64)
    for index, target in enumerate(loads):
        schedule = schedule_factory(float(target))
        truth = truth_simulator(schedule, physics_mode="structural_mismatch")
        prediction = model_predictor(model, schedule)
        true_values = np.asarray(getattr(truth, "hotspot_C"), dtype=np.float64)
        predicted_values = np.asarray(
            getattr(prediction, "hotspot_C"), dtype=np.float64
        )
        if (
            true_values.ndim != 1
            or predicted_values.shape != true_values.shape
            or true_values.size == 0
            or not np.all(np.isfinite(true_values))
            or not np.all(np.isfinite(predicted_values))
        ):
            raise ValueError("episode truth/prediction trajectories must align and be finite")
        true_peaks[index] = float(np.max(true_values))
        predicted_peaks[index] = float(np.max(predicted_values))
    return EpisodeBatch(
        target_loads_pu=_readonly(loads),
        true_peaks_C=_readonly(true_peaks),
        predicted_peaks_C=_readonly(predicted_peaks),
    )


def coverage_metrics_payload(metrics: CoverageMetrics) -> dict[str, object]:
    """Serialize coverage diagnostics without NaN for unavailable widths."""

    mean_width: float | None = (
        float(metrics.mean_finite_width)
        if np.isfinite(metrics.mean_finite_width)
        else None
    )
    median_width: float | None = (
        float(metrics.median_finite_width)
        if np.isfinite(metrics.median_finite_width)
        else None
    )
    return {
        "confidence_level": float(metrics.confidence_level),
        "empirical_coverage": float(metrics.empirical_coverage),
        "exact_binomial_ci_lower": float(metrics.exact_ci_lower),
        "exact_binomial_ci_upper": float(metrics.exact_ci_upper),
        "finite_availability": float(metrics.finite_availability),
        "mean_finite_upper_width_K": mean_width,
        "median_finite_upper_width_K": median_width,
        "n_covered": int(metrics.n_covered),
        "n_finite": int(metrics.n_finite),
        "n_total": int(metrics.n_total),
    }


def ratio_comparison_payload(
    estimated_ratio: ArrayLike, known_ratio: ArrayLike
) -> dict[str, object]:
    """Compare KDE-estimated and known synthetic density ratios."""

    estimated = np.asarray(estimated_ratio, dtype=np.float64)
    known = np.asarray(known_ratio, dtype=np.float64)
    if (
        estimated.ndim != 1
        or estimated.size == 0
        or estimated.shape != known.shape
        or not np.all(np.isfinite(estimated))
        or not np.all(np.isfinite(known))
    ):
        raise ValueError("estimated and known ratios must be aligned finite vectors")
    error = estimated - known
    if np.std(estimated, ddof=0) == 0.0 or np.std(known, ddof=0) == 0.0:
        correlation: float | None = None
    else:
        correlation = float(np.corrcoef(estimated, known)[0, 1])
    return {
        "bias": float(np.mean(error)),
        "correlation": correlation,
        "estimated_mean": float(np.mean(estimated)),
        "known_mean": float(np.mean(known)),
        "mean_absolute_error": float(np.mean(np.abs(error))),
        "n": int(error.size),
        "root_mean_square_error": float(np.sqrt(np.mean(error**2))),
        "worst_absolute_error": float(np.max(np.abs(error))),
    }


def _finite_or_none(value: float) -> float | None:
    return float(value) if np.isfinite(value) else None


def ordinary_case_payload(
    batch: EpisodeBatch,
    calibration_scores_K: ArrayLike,
    *,
    alpha: float = E5_ALPHA,
    confidence: float = E5_CONFIDENCE,
) -> dict[str, object]:
    """Aggregate one ordinary split-conformal episode case."""

    correction = one_sided_higher_quantile(calibration_scores_K, alpha=alpha)
    if not np.isfinite(correction):
        raise ValueError("ordinary E5 correction must be finite at the supplied sample size")
    limits = split_conformal_upper_limits(
        batch.predicted_peaks_C, calibration_scores_K, alpha=alpha
    )
    metrics = coverage_metrics(
        batch.true_peaks_C,
        batch.predicted_peaks_C,
        limits,
        confidence=confidence,
    )
    rows = [
        {
            "covered": bool(truth <= upper),
            "episode_index": index,
            "predicted_peak_C": float(prediction),
            "target_load_pu": float(load),
            "true_peak_C": float(truth),
            "upper_limit_C": float(upper),
            "upper_width_K": float(upper - prediction),
        }
        for index, (load, truth, prediction, upper) in enumerate(
            zip(
                batch.target_loads_pu,
                batch.true_peaks_C,
                batch.predicted_peaks_C,
                limits,
                strict=True,
            )
        )
    ]
    return {
        "correction_quantile_K": float(correction),
        "metrics": coverage_metrics_payload(metrics),
        "rows": rows,
    }


def weighted_case_payload(
    batch: EpisodeBatch,
    calibration_scores_K: ArrayLike,
    calibration_loads_pu: ArrayLike,
    calibration_weights: ArrayLike,
    target_weights: ArrayLike,
    calibration_densities_at_queries: ArrayLike,
    *,
    alpha: float = E5_ALPHA,
    confidence: float = E5_CONFIDENCE,
) -> dict[str, object]:
    """Aggregate weighted conformal limits, retaining infinity target mass."""

    results = weighted_conformal_upper_limits(
        batch.predicted_peaks_C,
        calibration_scores_K,
        calibration_weights,
        target_weights,
        alpha=alpha,
        query_loads=batch.target_loads_pu,
        calibration_loads=calibration_loads_pu,
        calibration_densities_at_queries=calibration_densities_at_queries,
    )
    numeric_limits = np.asarray(
        [result.upper_limit for result in results], dtype=np.float64
    )
    metrics = coverage_metrics(
        batch.true_peaks_C,
        batch.predicted_peaks_C,
        numeric_limits,
        confidence=confidence,
    )
    rows = []
    for index, (load, truth, prediction, result) in enumerate(
        zip(
            batch.target_loads_pu,
            batch.true_peaks_C,
            batch.predicted_peaks_C,
            results,
            strict=True,
        )
    ):
        rows.append(
            {
                "correction_quantile_K": _finite_or_none(
                    result.correction_quantile
                ),
                "covered": bool(truth <= result.upper_limit),
                "episode_index": index,
                "interval_status": "finite" if result.finite else "unbounded",
                "predicted_peak_C": float(prediction),
                "refusal_reason": result.refusal_reason,
                "target_infinity_mass": float(result.target_infinity_mass),
                "target_load_pu": float(load),
                "true_peak_C": float(truth),
                "upper_limit_C": _finite_or_none(result.upper_limit),
                "upper_width_K": (
                    float(result.upper_limit - prediction)
                    if result.finite
                    else None
                ),
            }
        )
    return {
        "calibration_weight_effective_sample_size": float(
            effective_sample_size(calibration_weights)
        ),
        "metrics": coverage_metrics_payload(metrics),
        "rows": rows,
    }


def strict_weighted_support_payload(
    batch: EpisodeBatch,
    calibration_scores_K: ArrayLike,
    calibration_loads_pu: ArrayLike,
    *,
    alpha: float = E5_ALPHA,
    confidence: float = E5_CONFIDENCE,
) -> dict[str, object]:
    """Return explicitly unbounded limits for strict support mismatch."""

    target_weights = np.ones(batch.target_loads_pu.size, dtype=np.float64)
    scores = np.asarray(calibration_scores_K, dtype=np.float64)
    # Under disjoint support q/p is undefined/infinite, so an overlapping-shift
    # ESS has no meaning here.  Positive placeholders only let the decisive
    # hull check execute; they are never used to form a finite quantile.
    placeholder_calibration_weights = np.ones(scores.shape, dtype=np.float64)
    # The observed-hull check is decisive.  A finite placeholder density is
    # supplied because no q/p ratio exists for a target outside P's support.
    densities = np.ones(batch.target_loads_pu.size, dtype=np.float64)
    payload = weighted_case_payload(
        batch,
        calibration_scores_K,
        calibration_loads_pu,
        placeholder_calibration_weights,
        target_weights,
        densities,
        alpha=alpha,
        confidence=confidence,
    )
    rows = payload["rows"]
    if not isinstance(rows, list) or any(
        row["interval_status"] != "unbounded"
        or row["refusal_reason"] != "query_outside_calibration_hull"
        or row["target_infinity_mass"] != 1.0
        for row in rows
    ):
        raise RuntimeError("strict weighted E5 support mismatch produced a finite limit")
    metrics = payload["metrics"]
    if not isinstance(metrics, dict) or (
        metrics["empirical_coverage"] != 1.0
        or metrics["finite_availability"] != 0.0
    ):
        raise RuntimeError("strict weighted E5 containment/availability invariant failed")
    payload["formal_containment_only_via_unbounded_limits"] = 1.0
    payload["calibration_weight_effective_sample_size"] = None
    payload["effective_sample_size_status"] = (
        "not defined for strict disjoint-support shift; no finite density ratio exists"
    )
    return payload


def _json_safe(value: object) -> object:
    """Recursively encode non-finite scalars without emitting invalid JSON."""

    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (float, np.floating)):
        number = float(value)
        if math.isnan(number):
            return None
        if math.isinf(number):
            return "positive_infinity" if number > 0.0 else "negative_infinity"
        return number
    return value


@record_primary_failures
def run_e5_primary(
    repository: str | Path,
    *,
    override: bool = False,
    override_reason: str | None = None,
) -> Mapping[str, object]:
    """Execute and persist the write-once preregistered E5 primary run."""

    enforce_cpu_only_environment()
    repository_path = Path(repository).resolve()
    configuration = e5_configuration()
    # Local import avoids coupling the pure E5 utilities to the neural
    # orchestrator while still enforcing the frozen E3 -> E2 -> E4 -> E5 order.
    from .experiments import (
        E2_SEEDS,
        E3_SEEDS,
        E4_SEEDS,
        e2_configuration,
        e3_configuration,
        e4_configuration,
        _recorded_primary_command,
    )

    require_e1_passed(repository_path)
    require_completed_primary(
        repository_path,
        "e3",
        required_configuration=e3_configuration(),
        required_seeds=E3_SEEDS,
    )
    require_completed_primary(
        repository_path,
        "e2",
        required_configuration=e2_configuration(),
        required_seeds=E2_SEEDS,
    )
    require_completed_primary(
        repository_path,
        "e4",
        required_configuration=e4_configuration(),
        required_seeds=E4_SEEDS,
    )
    run = begin_primary_run(
        repository_path,
        experiment="e5",
        configuration=configuration,
        seeds=[E5_SEED],
        command=_recorded_primary_command(
            "e5", override=override, override_reason=override_reason
        ),
        override=override,
        override_reason=override_reason,
    )

    # The sentinel above is durable before any episode truth is generated.
    model = fit_e5_nls_once(seed=E5_SEED)
    draws = draw_e5_episode_loads(seed=E5_SEED)
    validate_primary_episode_draws(draws)

    calibration = evaluate_episode_loads(draws.calibration_loads_pu, model)
    calibration_scores = calibration.conformity_scores_K
    exchangeable = evaluate_episode_loads(
        draws.exchangeable_test_loads_pu, model
    )
    exchangeable_payload = ordinary_case_payload(
        exchangeable, calibration_scores
    )
    exchangeable_metrics = exchangeable_payload["metrics"]
    assert isinstance(exchangeable_metrics, dict)
    exchangeable_metrics["nominal_0_95_inside_exact_ci"] = bool(
        exchangeable_metrics["exact_binomial_ci_lower"]
        <= 0.95
        <= exchangeable_metrics["exact_binomial_ci_upper"]
    )

    strict_payloads: list[dict[str, object]] = []
    strict_batches: list[tuple[float, EpisodeBatch]] = []
    for centre, loads in draws.strict_test_loads_by_centre:
        batch = evaluate_episode_loads(loads, model)
        strict_batches.append((centre, batch))
        ordinary = ordinary_case_payload(batch, calibration_scores)
        ordinary["band_centre_pu"] = centre
        ordinary["band_lower_pu"] = centre - E5_STRICT_BAND_WIDTH_PU / 2.0
        ordinary["band_upper_pu"] = centre + E5_STRICT_BAND_WIDTH_PU / 2.0
        strict_payloads.append(ordinary)

    # Fit each KDE once on the same 200 calibration and 2,000 unlabeled target
    # loads, then evaluate both the calibration and weighted-test covariates.
    ratio_evaluation_loads = np.concatenate(
        (calibration.target_loads_pu, draws.weighted_test_loads_pu)
    )
    ratio_estimate = gaussian_kde_scott_density_ratio(
        calibration.target_loads_pu,
        draws.unlabeled_target_loads_pu,
        ratio_evaluation_loads,
    )
    n_calibration = calibration.target_loads_pu.size
    calibration_weights = ratio_estimate.density_ratio[:n_calibration]
    weighted_target_weights = ratio_estimate.density_ratio[n_calibration:]
    weighted_target_densities = ratio_estimate.calibration_density[n_calibration:]
    if not np.all(np.isfinite(calibration_weights)):
        raise FloatingPointError(
            "KDE ratio at a calibration observation is non-finite; weighted calibration is unavailable"
        )
    observed_lower = float(np.min(calibration.target_loads_pu))
    observed_upper = float(np.max(calibration.target_loads_pu))
    finite_required = (
        (draws.weighted_test_loads_pu >= observed_lower)
        & (draws.weighted_test_loads_pu <= observed_upper)
        & (weighted_target_densities > np.finfo(np.float64).tiny)
    )
    if np.any(finite_required & ~np.isfinite(weighted_target_weights)):
        raise FloatingPointError(
            "overlapping KDE ratio is non-finite without a support-refusal condition"
        )

    weighted_batch = evaluate_episode_loads(draws.weighted_test_loads_pu, model)
    weighted_payload = weighted_case_payload(
        weighted_batch,
        calibration_scores,
        calibration.target_loads_pu,
        calibration_weights,
        weighted_target_weights,
        weighted_target_densities,
    )
    known_all = np.asarray(
        beta_5_2_mapped_density_ratio(ratio_evaluation_loads), dtype=np.float64
    )
    weighted_payload["estimated_vs_known_ratio_at_calibration_loads"] = (
        ratio_comparison_payload(
            calibration_weights,
            known_all[:n_calibration],
        )
    )
    weighted_payload["estimated_vs_known_ratio_at_test_loads"] = (
        ratio_comparison_payload(
            weighted_target_weights,
            known_all[n_calibration:],
        )
    )
    weighted_rows = weighted_payload["rows"]
    assert isinstance(weighted_rows, list)
    for index, row in enumerate(weighted_rows):
        row["estimated_density_ratio"] = float(weighted_target_weights[index])
        row["known_density_ratio"] = float(known_all[n_calibration + index])

    weighted_strict_payloads: list[dict[str, object]] = []
    for centre, batch in strict_batches:
        payload = strict_weighted_support_payload(
            batch,
            calibration_scores,
            calibration.target_loads_pu,
        )
        payload["band_centre_pu"] = centre
        payload["band_lower_pu"] = centre - E5_STRICT_BAND_WIDTH_PU / 2.0
        payload["band_upper_pu"] = centre + E5_STRICT_BAND_WIDTH_PU / 2.0
        weighted_strict_payloads.append(payload)

    calibration_rows = [
        {
            "conformity_score_K": float(score),
            "episode_index": index,
            "estimated_density_ratio": float(calibration_weights[index]),
            "known_density_ratio": float(known_all[index]),
            "predicted_peak_C": float(prediction),
            "target_load_pu": float(load),
            "true_peak_C": float(truth),
        }
        for index, (load, truth, prediction, score) in enumerate(
            zip(
                calibration.target_loads_pu,
                calibration.true_peaks_C,
                calibration.predicted_peaks_C,
                calibration_scores,
                strict=True,
            )
        )
    ]
    aggregate = _json_safe(
        {
            "calibration": {
                "conformity_quantile_K": one_sided_higher_quantile(
                    calibration_scores, alpha=E5_ALPHA
                ),
                "rows": calibration_rows,
            },
            "configuration": configuration,
            "exchangeable_in_range": exchangeable_payload,
            "interpretation_guards": {
                "exchangeable_exact_marginal_coverage_claim": True,
                "kde_weighted_exact_coverage_claim": False,
                "kde_weighted_reason": (
                    "estimated density ratios do not automatically inherit the "
                    "oracle finite-sample theorem"
                ),
                "strict_shift_exact_coverage_claim": False,
                "strict_weighted_finite_guarantee_claim": False,
            },
            "nls_fit": model.as_dict(),
            "schema_version": 1,
            "strict_ordinary_shift": {"bands": strict_payloads},
            "weighted_overlapping_shift": weighted_payload,
            "weighted_strict_support_mismatch": {
                "bands": weighted_strict_payloads
            },
        }
    )
    assert isinstance(aggregate, dict)
    final = finish_primary_run(run, aggregate)
    return {"aggregate": aggregate, "manifest": dict(final), "run_id": run.run_id}


__all__ = [
    "E5_ALPHA",
    "E5_CALIBRATION_EPISODES",
    "E5_CONFIDENCE",
    "E5_IN_RANGE_SUPPORT_PU",
    "E5_REFERENCE_BUDGET",
    "E5_SEED",
    "E5_STRICT_BAND_WIDTH_PU",
    "E5_STRICT_CENTRES_PU",
    "E5_TEST_EPISODES",
    "E5_UNLABELED_TARGET_EPISODES",
    "E5EpisodeDraws",
    "EpisodeBatch",
    "coverage_metrics_payload",
    "draw_e5_episode_loads",
    "e5_configuration",
    "evaluate_episode_loads",
    "fit_e5_nls_once",
    "make_e5_episode_schedule",
    "ordinary_case_payload",
    "ratio_comparison_payload",
    "run_e5_primary",
    "strict_weighted_support_payload",
    "validate_primary_episode_draws",
    "weighted_case_payload",
]
